### ISSUE TITLE
Version 1.13.65 CANT put INTERFACE WINDOW UP and more

### ISSUE THREAD

**Issue by Psihotank** [DeadlyBossMods/DBM-Classic#662] opened 2021-01-07 10:31 UTC
Version 1.13.64 works fine, but 1.13.65 version , If I press /dbm , nothing happends....also, when clicking while in Warcraft game on Main menu icon/interface options/ addons, DBM in NOT among other addons. also, when clicking on minimap DBM icon, nothing happends.....Please fix this issue

Please fix this!!!

VIDEO ATTACHED.

https://user-images.githubusercontent.com/77101421/103882256-d2d27580-50db-11eb-8661-b7edc3924c7c.mp4

**Comment by QartemisT** [comment] 2021-01-07 12:59
Could you post a picture of your addons list (which can be found by hitting esc) showing both dbm core and gui and all dependencies

**Comment by Psihotank** [comment] 2021-01-07 16:20
I dont know exactly where you meant me to press excape, but here is list of my addons to be loaded, it looks like this, I never changed anything for months, untill this 1.13.65 version updated recently and brought thid problem....
here is 2 fotos attached .....
![IMG_20210107_1649029](https://user-images.githubusercontent.com/77101421/103916311-8f442f80-510c-11eb-98bc-63f55ed6cf90.jpg)
![IMG_20210107_1649070](https://user-images.githubusercontent.com/77101421/103916347-9bc88800-510c-11eb-9207-d7383a7093b4.jpg)

**Comment by MysticalOS** [comment] 2021-01-07 16:21
Can you pull up DBM gui turning off other addons? at this point maybe a conflict is at play, because we can't reproduce this issue

**Comment by Psihotank** [comment] 2021-01-07 16:54
Hello Mystical. I dissabled ALL addons except DBM . still SAME ISSUE. there is DBM Icon on minimap, but It canNOT be clicked. 
also, there is no DBM 'Welcome message' when game entered, however, welcome message shows when entering any dungeon, but STILL cant access GUI via Icon on minimap, nor via /dbm command....
I guess I am screwed.

**Comment by anon1231823** [comment] 2021-01-07 18:40
I had the same issue

**Comment by MysticalOS** [comment] 2021-01-07 22:57
Fixed by @QartemisT in latest commit, closing issue. New release going out soon

**Closed by MysticalOS** 2021-01-07 22:57 UTC
Labels: ⚠️ High Priority, 🐛 Bug
