### ISSUE TITLE
Classic Era 1.14.4 AV Turn In Quest Bug

### ISSUE THREAD

**Issue by maddhacker24** [DeadlyBossMods/DBM-Classic#775] opened 2023-09-13 20:38 UTC
When trying to turn in Blood, Armor Scraps and other quest items in Alterac Valley this error is thrown every time.

The automatic turn in also doesn't work because of this.

135x DBM-PvP/Battlegrounds/Alterac.lua:91: attempt to call upvalue 'GetNumGossipActiveQuests' (a nil value)
[string "@DBM-PvP/Battlegrounds/Alterac.lua"]:91: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:1053: in function <DBM-Core/DBM-Core.lua:1040>

Locals:
self =

{
CHAT_MSG_MONSTER_YELL = defined @DBM-PvP/Battlegrounds/Alterac.lua:121
timers =
{
}
categorySort =
{
}
OnInitialize = defined @DBM-PvP/Battlegrounds/Alterac.lua:48
PLAYER_ENTERING_WORLD = defined @DBM-PvP/Battlegrounds/Alterac.lua:48
SyncThreshold = 8
LOADING_SCREEN_DISABLED = defined @DBM-PvP/Battlegrounds/Alterac.lua:48
modId = "DBM-PvP"
groupSpells =
{
}
GOSSIP_SHOW = defined @DBM-PvP/Battlegrounds/Alterac.lua:82
shortTermRegisterEvents =
{
}
stats =
{
}
revision = 20230110015611
Options =
{
}
DefaultOptions =
{
}
id = "z30"
QUEST_COMPLETE = defined @DBM-PvP/Battlegrounds/Alterac.lua:113
ZONE_CHANGED_NEW_AREA = defined @DBM-PvP/Battlegrounds/Alterac.lua:48
QUEST_PROGRESS = defined @DBM-PvP/Battlegrounds/Alterac.lua:106
addon =
{
}
groupOptions =
{
}
specwarns =
{
}
iconRestore =
{
}
localization =
{
}
announces =
{
}
vb =
{
}
optionCategories =
{
}
}
quest =
{
1 =
{
}
2 =
{
}
}
(for generator) = defined =[C]:-1
(for state) =
{
1 =
{
}
2 =
{
}
}
(for control) = 1
_ = 1
v =
{
1 = 17306
2 = 5
}
num = 39
(*temporary) = nil
(*temporary) = "attempt to call upvalue 'GetNumGossipActiveQuests' (a nil value)"
quests =
{
13442 =
{
}
13236 =
{
}
13180 =
{
}
13257 =
{
}
13439 =
{
}
13441 =
{
}
13577 =
{
}
13176 =
{
}
13179 =
{
}
13181 =
{
}
13438 =
{
}
13437 =
{
}
}
UnitGUID = defined =[C]:-1
type = defined =[C]:-1
ipairs = defined =[C]:-1
GetItemCount = defined =[C]:-1
GetNumGossipActiveQuests = nil
SelectGossipActiveQuest = nil
SelectGossipAvailableQuest = nil

**Comment by QartemisT** [comment] 2023-09-13 20:55
Duplicate of https://github.com/DeadlyBossMods/DBM-PvP/issues/118

**Closed by QartemisT** 2023-09-13 20:55 UTC
